### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by DGollings** [liff/jetbrains-flake#32]
Hi, 

Found this repo and looks good, except that I have no idea how to use it :)
There's a package.json, but I don't see how I would get it to install Goland 2022.1.4 using an array for example.

Could you add an example flake.nix using this flake? 

Thanks

ps. maybe add to https://search.nixos.org/flakes ?

**Comment by liff** [comment]
If you are running NixOS you can use the module:

```nix
{
  inputs.jetbrains.url = "github:liff/jetbrains-flake";

  outputs = { self, nixpkgs, jetbrains }: {
    # replace 'joes-desktop' with your hostname here.
    nixosConfigurations.joes-desktop = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
        # …
        jetbrains.nixosModules.default
      ];
    };
  };
}
```

That module adds an overlay to nixpkgs with the packages from this flake, which you can then use in `environment.systemPackages`.

Alternatively you could install with `nix profile install`, I think, but I don’t use it myself.

You can see the list of packages in this flake with:

```shell
$ nix flake show --no-write-lock-file github:liff/jetbrains-flake
```

All that said, there is no Goland package here yet as I haven’t needed it thus far.

**Comment by DGollings** [comment]
shame, had a look around but by Nix knowledge is not sufficient to add that package either. Thanks though
